sudo: required
services:
  - docker

before_install:
  - docker build -t hashsix/docker-react -f Dockerfile.dev .

script:
  - docker run hashsix/docker-react npm run test-ci

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-148167448280" 
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
